name: nsp2021
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=1.0
  - jupyter=1.0.0
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.2.2
  - pillow=8.1.1
  - pip=21.0.1
  - python=3.7.9
  - pytorch=1.8.0
  - scipy=1.5.2
  - torchaudio=0.8.0
  - torchvision=0.9.0
  - pip:
    - pyro-ppl==1.6.0
    - numba==0.53.1
    - stingray==0.2
